### PR TITLE
Use 'readlink -e' to support symlinks

### LINKED ISSUE #50: `$script_dir` should be defined after resolving the real path of the script, because the script could be used through a symlink
`$script_dir` should be defined after resolving the real path of the script, because the script could be used through a symlink.

Like this:
```
script_dir="$(cd "$(dirname $(realpath "${BASH_SOURCE[0]}"))" && pwd)" || die "Couldn't determine the script's running directory, which probably matters, bailing out" 2
```

### PR DESCRIPTION
**Pull request by Conduitry**
Fixes #50. This adds a call to realpath so that argbash can be called from a symlink.

It also adds a realpath call to the scripts generated by argbash-init in complete parsing separation mode.

Let me know if you'd prefer the rebuild commit to be combined into the first commit, or if you'd prefer it to not be in the PR at all.

### CODE REVIEW

**Comment by Conduitry** [comment]
I'm not sure what the test failure is here, I'm having trouble interpreting the output.

When I run `make -B ../tests/regressiontests/Makefile && make check ARGBASH_EXEC=argbash ARGBASH_INIT_EXEC=argbash-init` locally, I don't see any failures, and the build ends with `*** All is OK ***`.

**Comment by Conduitry** [comment]
Just went with `readlink -e`, and the tests pass now.

**Comment by Conduitry** [comment]
Sorry for the comment spam!

One (hopefully) last thing. I realized I wasn't too sure about what all of the different built files were, so I've just removed that commit and will leave that part up to you.

**Comment by matejak** [comment]
Thank you once again, I like your work, you have made the right decision of going for a solution that is more portable, as the `realpath` situation is a bit confused. I am also curious about what was the removed commit originally about.
I intend to merge your PR, but I would really love you to update the `ChangeLog` as well as the `AUTHORS` file.

**Comment by Conduitry** [comment]
Updated `ChangeLog` and `AUTHORS`!

The removed commit I mentioned was just the rebuilding of the scripts in `bin` - but I realized that I had missed rebuilding things in `resources/examples`, and so I decided to just let you take care of that when you cut the release or whenever you wanted.

**Comment by matejak** [comment]
Great, that makes sense. Thank you for your contribution!

**Pull request merged**
