### PR TITLE
[docs] Spelling and typos fixes

### PR DESCRIPTION
**Pull request by btamayo**
Minor spelling and typo fixes.

I think this project is great by the way. I've been looking for something like this for a long time! When I read through the docs, I think it takes a bit of effort to understand how to start to use and write the template. I'm fixing typos and spelling right now only, but I'd be happy to work on updating the docs so that it's easier to understand how to immediately use `argbash` if that's something you're willing to have. :)

### CODE REVIEW

**Comment by matejak** [comment]
Wow, that's an awful number of spelling errors!
Thank you very much for your effort, I really appreciate that. I will leave this PR opened longer, so you don't have to open them all over again.
I have put an effort to make Argbash as accessible as possible, but I am convinced that it takes more people to find the right way how to explain things. I am very grateful for your commitment and I am sure that Argbash will benefit even more people thanks to your effort.

**Comment by btamayo** [comment]
@matejak It's my pleasure! I think this project is super helpful and I want more people to know about it. I'll try to help more with docs as I get time :)

**Comment by btamayo** [comment]
@matejak Trying to confirm something: To use `Argbash`, you need to clone this repository and then run it using the executables in `bin`. Is that right? That is, I'm checking if argbash has been submitted to a package management repo, such as Homebrew.

**Comment by matejak** [comment]
Hello, in order to use Argbash, you don't have to clone the repository - you can [download an argbash release](https://github.com/matejak/argbash/releases). Or you can use the [online parsing code generator](https://argbash.io/generate).
Argbash is available in Archlinux user repository (AUR) and it may appear in Fedora at some point. I have not made an effort to push it to Homebrew, but it is my long-term vision and help on this matter will be appreciated.

**Comment by matejak** [comment]
Regarding building and installation:
As far as I understand those terms, no Argbash user needs to `build` argbash. As you have found out, one has to download the package/clone the repository, and there already is the fully functional `argbash` script (i.e. there is nothing that needs to be built).
The installation as I understand is a process in which executable and support files are placed in the host system in a way in which the software becomes integrated with it (i.e. scripts can be easily called from the terminal, GUI apps become accessible through menus etc.). In this sense, running `make install` is installation, because it copies files to the system and makes minimal path-related alternations to the underlying code. Does this make sense to you?
I appreciate your remark that the information on how to get the software is missing - you are totally right on that! And this will be more and more true as the number of ways how to get it will expand.

**Comment by btamayo** [comment]
> In this sense, running make install is installation, because it copies files to the system and makes minimal path-related alternations to the underlying code. Does this make sense to you?

This totally makes sense to me and I understand completely. I'm mostly trying to mimic the expectations that users generally have with open source modules that I've noticed.

In general, this is the pattern I've become used to when browsing open-source module documentation with regards to Installing for users and for developers:

---

## **1. Installation Section**
The installation section is to tell **users** how to download and execute their program (installing for _usage_). For example, this section, I usually see instructions to install using `brew` or `apt-get`, etc.

Sometimes, when "Installation" as a word doesn't make sense, it's replaced by "Usage", or "Quick Start", but when "Installation" isn't used, no other section is called "Installation" to prevent confusion. 

I think it's called "Installation" because it copies the _built_ artifacts to the right paths in a user's system, and it makes sense to end users because they're used to "installing" apps and packages on their computer.

## **2. Build Section** 
The "Build" section tells _developers_ how to **download** and work on the pre-built code for the repository, and build it. It also tells developers how to set up a dev environment and build the code (e.g. `make`). 

I've also seen this section called "Development", "Developer Install", "Installing from Source" (being clear that it's different from normal Installing) and "Contributing". 

If it's a big section, it's sometimes separated out to it's own page or file.

---

I think it would be a good idea to conform to this pattern so that people would more quickly understand the docs. Again, I would be happy to help restructure the docs. Let me know your thoughts :) 

Examples:
- [Requests](https://github.com/requests/requests)
- [React](https://github.com/facebook/react)
- [Vagrant](https://github.com/mitchellh/vagrant)

**Comment by btamayo** [comment]
As with submitting to package managers, I'd be happy to help with that :)

**Comment by matejak** [comment]
It is great to see that we are mostly on the same page: So let me summarize:
- The installation section in its current form in the Argbash manual indeed describes what is commonly understood as installation. However, it misses the "how to get Argbash" instructions.
- The building section doesn't exist, which is unfortunate, because it could be useful for contributors.
- The `make check` part of theinstallation section could go to the build section.
Regarding submissions to package managers, please start doing that if you can. I will be happy to help, there already is some support code for package maintainers under `resources/packages`, so little extra of coding work is required to create the package metadata.

**Comment by btamayo** [comment]
@matejak Yes, we're on the same page. :+1: And I'd be happy to!

**Pull request merged**
